org: genuinesnipe
console: true
service: aws-lambda-afex-youtube
frameworkVersion: '3'

provider:
  name: aws
  runtime: nodejs14.x
  region: us-west-2
  iamRoleStatements:
    - Effect: Allow
      Action:
        - dynamodb:*
      Resource:
        - arn:aws:dynamodb:us-west-2:590552402639:table/videos

functions:
  hello:
    handler: src/handler.hello
    events:
      - httpApi:
          path: /
          method: get
  createVideo:
    handler: src/addVideo.createVideo
    events:
      - httpApi:
          path: /videos
          method: post
  getVideos:
    handler: src/getVideos.getVideos
    events:
      - httpApi:
          path: /videos
          method: get
  deleteVideo:
    handler: src/deleteVideo.deleteVideo
    events:
      - httpApi:
          path: /videos/{id}
          method: delete

resources:
  Resources:
    videos:
      Type: AWS::DynamoDB::Table
      Properties:
        TableName: videos
        BillingMode: PAY_PER_REQUEST
        AttributeDefinitions:
          - AttributeName: id
            AttributeType: S
        KeySchema:
          - AttributeName: id
            KeyType: HASH